# Basic settings
data_dir: /home/jinxiaolong/bl/data/new_scripts
work_dir: /home/jinxiaolong/bl/data/resep_data
pb_dir: /home/jinxiaolong/bl/data/propbank-frames
progress_bar: True
overwrite: False

# Preprocess settings
preprocess:
  min_freq: 10
  seed: 10000019

# Model settings
model:
  type: pmi
  name: pmi
  # Though listed, these args are not used in pmi
  lr: 1.0e-2
  weight_decay: 1.0e-3
  npoch: 20
  batch_size: 1000
  interval: 50
  vocab_size: 51952
  embedding_dim: 300
  event_dim: 300
  seq_len: 8
  dropout: 0.1
  # Args used in pmi
  ordered: False
  event_threshold: 20
  pair_threshold: 20
